name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-template.yml
    with:
      artifact_prefix: release
      retention_days: 1
    secrets:
      env_content: ${{ secrets.ENV_FILE_CONTENT }}

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from pyproject
        shell: bash
        run: |
          chmod +x scripts/get-version
          echo "VERSION=$(scripts/get-version)" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Bloquinhos - v${{ env.VERSION }}
          generate_release_notes: true
          body_path: .github/release-body.md
          files: |
            release-windows/*.exe
            release-linux/*.deb
            release-linux/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
