name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Package ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: linux
          - os: windows-latest
            artifact_name: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: block_env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Create .env file from Secrets
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Install nFPM
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          VERSION=v2.37.1
          curl -fL https://github.com/goreleaser/nfpm/releases/download/${VERSION}/nfpm_${VERSION#v}_amd64.deb -o nfpm.deb
          sudo dpkg -i nfpm.deb
          nfpm --version

      - name: Set VERSION
        run: echo "VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml | head -1)" >> $GITHUB_ENV

      - name: Build executable
        run: make build

      - name: Package
        run: make package VERSION=${{ env.VERSION }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            *.exe
            *.deb
            *.rpm

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from pyproject
        shell: bash
        run: echo "VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml | head -1)" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Bloquinhos - v${{ env.VERSION }}
          generate_release_notes: true
          body_path: .github/release-body.md
          files: |
            windows/*.exe
            linux/*.deb
            linux/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
